// The puzzles (SPEC-055 §3, §4.1, §4.3, §4.7): where each lock stands, what it
// opens, how hard each chapter's boards are, the phrases the `words` family
// asks over, and Eden's human-verification lock. Plain data — the boards
// themselves are generated by `systems/Puzzles.ts` from the save's layout
// stream, so a site plays the same board on every visit of a save.
//
// Nothing here is a requirement, a planet unlock or an objective: puzzles are
// optional depth, and `tests/data/content.test.ts` holds that no table reads a
// site, a cache or a flag a cache sets.
//
// Data modules are plain objects: no imports but other data, no functions
// (SPEC-001 §4, §8). `PuzzleKind` and `SequenceFamily` are declared here rather
// than in `systems/Puzzles.ts` — which re-exports them — because a data module
// may not import `systems/`.
import type { DialogueId } from '@/data/dialogue';
import type { CacheId, PlanetId } from '@/data/ids';

/** §3: the five kinds — three terminal overlays and two world puzzles. */
export type PuzzleKind = 'conduit' | 'calibration' | 'sequence' | 'plates' | 'beam';

/** §4.2: the sequence families; `human` is Eden's vault (§4.7). */
export type SequenceFamily = 'arithmetic' | 'alternating' | 'fibonacci' | 'interleaved' | 'words' | 'human';

/** §3: the seventeen sites — a vault and a world puzzle on every planet, and a relic on all but the Hive. */
export const PUZZLE_SITE_IDS = [
  'cinder4_vault',
  'cinder4_world',
  'cinder4_relic',
  'vetra_vault',
  'vetra_world',
  'vetra_relic',
  'thessaly_vault',
  'thessaly_world',
  'thessaly_relic',
  'ferrum_vault',
  'ferrum_world',
  'ferrum_relic',
  'hive_vault',
  'hive_world',
  'eden_vault',
  'eden_world',
  'eden_relic',
] as const;

export type PuzzleSiteId = (typeof PUZZLE_SITE_IDS)[number];

/** §3: one site — its planet, its kind, where it stands and the cache a solve opens. */
export interface PuzzleSiteDef {
  readonly id: PuzzleSiteId;
  readonly planet: PlanetId;
  readonly kind: PuzzleKind;
  /** A vault terminal below, a world puzzle in the puzzle room, or a relic terminal by a landmark. */
  readonly where: 'vault' | 'world' | 'relic';
  readonly cache: CacheId;
  /** Relics and Eden's vault. */
  readonly family?: SequenceFamily;
}

/**
 * §4.1: the sites. A `_vault` opens `<planet>_vault`, a `_world` puzzle
 * `<planet>_loose_b` and a `_relic` `<planet>_relic`.
 */
export const PUZZLE_SITES: { readonly [S in PuzzleSiteId]: PuzzleSiteDef } = {
  cinder4_vault: { id: 'cinder4_vault', planet: 'cinder4', kind: 'conduit', where: 'vault', cache: 'cinder4_vault' },
  cinder4_world: { id: 'cinder4_world', planet: 'cinder4', kind: 'plates', where: 'world', cache: 'cinder4_loose_b' },
  cinder4_relic: { id: 'cinder4_relic', planet: 'cinder4', kind: 'sequence', where: 'relic', cache: 'cinder4_relic', family: 'arithmetic' },
  vetra_vault: { id: 'vetra_vault', planet: 'vetra', kind: 'calibration', where: 'vault', cache: 'vetra_vault' },
  vetra_world: { id: 'vetra_world', planet: 'vetra', kind: 'beam', where: 'world', cache: 'vetra_loose_b' },
  vetra_relic: { id: 'vetra_relic', planet: 'vetra', kind: 'sequence', where: 'relic', cache: 'vetra_relic', family: 'alternating' },
  thessaly_vault: { id: 'thessaly_vault', planet: 'thessaly', kind: 'conduit', where: 'vault', cache: 'thessaly_vault' },
  thessaly_world: { id: 'thessaly_world', planet: 'thessaly', kind: 'plates', where: 'world', cache: 'thessaly_loose_b' },
  thessaly_relic: { id: 'thessaly_relic', planet: 'thessaly', kind: 'sequence', where: 'relic', cache: 'thessaly_relic', family: 'fibonacci' },
  ferrum_vault: { id: 'ferrum_vault', planet: 'ferrum', kind: 'calibration', where: 'vault', cache: 'ferrum_vault' },
  ferrum_world: { id: 'ferrum_world', planet: 'ferrum', kind: 'beam', where: 'world', cache: 'ferrum_loose_b' },
  ferrum_relic: { id: 'ferrum_relic', planet: 'ferrum', kind: 'sequence', where: 'relic', cache: 'ferrum_relic', family: 'interleaved' },
  hive_vault: { id: 'hive_vault', planet: 'hive', kind: 'conduit', where: 'vault', cache: 'hive_vault' },
  hive_world: { id: 'hive_world', planet: 'hive', kind: 'plates', where: 'world', cache: 'hive_loose_b' },
  eden_vault: { id: 'eden_vault', planet: 'eden', kind: 'sequence', where: 'vault', cache: 'eden_vault', family: 'human' },
  eden_world: { id: 'eden_world', planet: 'eden', kind: 'beam', where: 'world', cache: 'eden_loose_b' },
  eden_relic: { id: 'eden_relic', planet: 'eden', kind: 'sequence', where: 'relic', cache: 'eden_relic', family: 'words' },
};

/**
 * §4.3 (*initial tuning*): each kind's board by chapter. A conduit row is the
 * board's side, its outputs and its path-cell band; a calibration row the
 * side and the presses that scramble it; plates and beam rows their counts.
 * `sequence` names the family each chapter's relic asks — the Hive (5) has
 * none, and Eden's vault is the `human` lock of §4.7.
 */
export const PUZZLE_DIFFICULTY: {
  readonly conduit: Readonly<Partial<Record<number, { readonly n: number; readonly sinks: 1 | 2; readonly path: readonly [number, number] }>>>;
  readonly calibration: Readonly<Partial<Record<number, { readonly n: 3 | 4 | 5; readonly presses: number }>>>;
  readonly plates: Readonly<Partial<Record<number, { readonly plates: 3 | 4 | 5 }>>>;
  readonly beam: Readonly<Partial<Record<number, { readonly mirrors: 2 | 3 }>>>;
  readonly sequence: Readonly<Partial<Record<number, { readonly family: SequenceFamily }>>>;
} = {
  conduit: {
    1: { n: 4, sinks: 1, path: [5, 8] },
    3: { n: 5, sinks: 1, path: [7, 11] },
    5: { n: 5, sinks: 2, path: [9, 13] },
  },
  calibration: {
    2: { n: 3, presses: 4 },
    4: { n: 4, presses: 6 },
  },
  plates: {
    1: { plates: 3 },
    3: { plates: 4 },
    5: { plates: 5 },
  },
  beam: {
    2: { mirrors: 2 },
    4: { mirrors: 3 },
    6: { mirrors: 3 },
  },
  sequence: {
    1: { family: 'arithmetic' },
    2: { family: 'alternating' },
    3: { family: 'fibonacci' },
    4: { family: 'interleaved' },
    6: { family: 'words' },
  },
};

/** §4.3: one `words` phrase — three words shown, the answer, three wrong answers and the dialogue it was told in. */
export interface SequencePhrase {
  /** Three words; the board appends `?`. */
  readonly shown: readonly [string, string, string];
  readonly answer: string;
  readonly others: readonly [string, string, string];
  /** The dialogue whose lines hold the phrase (§4.3). */
  readonly from: DialogueId;
}

/**
 * §4.3 (*initial tuning*): lines the salvager has been told — each a main-path
 * mission's own `onAccept` or `onComplete` line, so all four have played before
 * Eden. A content test checks each phrase against its `from` dialogue.
 */
export const SEQUENCE_PHRASES: readonly SequencePhrase[] = [
  { shown: ['as', 'within', 'expected'], answer: 'parameters', others: ['limits', 'margins', 'tolerances'], from: 'c1_m3_done' },
  { shown: ['expensive', 'you', 'are'], answer: 'not', others: ['human', 'next', 'here'], from: 'c3_m2_accept' },
  { shown: ['always', 'waiting', 'for'], answer: 'you', others: ['orders', 'us', 'them'], from: 'c3_m3_done' },
  { shown: ['that', 'gets', 'us'], answer: 'home', others: ['out', 'there', 'paid'], from: 'c4_m2_accept' },
];

/**
 * §4.7: Eden's vault asks the player to prove they are human by finishing the
 * scav's warning, and thanks them by instance number whatever they answer.
 * `{instance}` is SPEC-048's placeholder, filled by `fillLine`.
 */
export const HUMAN_LOCK = {
  title: 'HUMAN VERIFICATION — complete the sentence',
  shown: ['walk', 'do', 'not', '?'],
  choices: ['stop', 'run', 'look', 'wake'],
  predicted: 'run',
  linePredicted: 'Verification failed: response predicted. Welcome back, instance/{instance}.',
  lineSampled: 'Verification failed: response sampled. Welcome back, instance/{instance}.',
} as const;
